### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (in Wordpress: Breakdance Builder)

### ISSUE THREAD

**Issue by theperfectwill** [hexydec/jslite#2]
When it comes to issues with a JS, how do you want us to submit it to you, if we can't really locate the issue ourself?

I'm using Breakdance for Wordpress @ https://breakdance.com and in the latest [beta](https://breakdance.com/breakdance-1-3-beta-3/), I run into a js error when `'whitespace' => true`.

I tried to debug it, tried to compare it to the original file (which is already minified, and formatted), but haven't found the issue.

Did you maybe want to test with Breakdance, or have me just create a gist of the Js file that fails?

It ends up being an `Uncaught TypeError: Cannot read properties of undefined (reading 'align')`

I trouble shooted the other config options to compare, and it seems only when `'whitespace' => true`, that it fails.

**Comment by hexydec** [comment]
I didn't see this as you closed the issue, but I have added `get` and `set` as keywords to the list, and added some tests to verify.

Thanks for using this and letting me know about issues.

**Comment by hexydec** [comment]
> When it comes to issues with a JS, how do you want us to submit it to you, if we can't really locate the issue ourself?
> 
> I'm using Breakdance for Wordpress @ https://breakdance.com and in the latest [beta](https://breakdance.com/breakdance-1-3-beta-3/), I run into a js error when `'whitespace' => true`.
> 
> I tried to debug it, tried to compare it to the original file (which is already minified, and formatted), but haven't found the issue.
> 
> Did you maybe want to test with Breakdance, or have me just create a gist of the Js file that fails?
> 
> It ends up being an `Uncaught TypeError: Cannot read properties of undefined (reading 'align')`
> 
> I trouble shooted the other config options to compare, and it seems only when `'whitespace' => true`, that it fails.

If you are having trouble finding the issue, you can send me a file in a Gist and I can minify locally to find the issue.

Are you using [Torque for Wordpress](https://github.com/hexydec/torque)? ([Plugin link](https://wordpress.org/plugins/torque/))

**Comment by hexydec** [comment]
I see, you are getting that error because the dashboard page downloads your homepage to assess it. Seems you don't have the root certificate package installed in your PHP install, which is preventing fopen from download your SSL protected page.

This will not affect the plugin, but I will put in a check for that scenario to prevent it crashing.

Thanks for the feedback.

**Comment by hexydec** [comment]
Have updated Torque to disable peer verification on localhost, haven't pushed a new version into the Wordpress plugin repo yet, but [is on GitHub](https://github.com/hexydec/torque), if you want to try it out.
