### ISSUE TITLE
Minification fails on a particular jQuery line

### ISSUE THREAD

**Issue by theperfectwill** [hexydec/jslite#3]
Hi.

I'm working with Wordpress, and I found that my minification routines were failing now when trying to minify jQuery. I know that jQuery should be avoided to minify, because jQuery already has a minified version in Wordpress, but I noticed either Wordpress or a plugin is loading the unminifed version of jQuery. I've fixed that in my own methods to skip trying to minify jQuery and scripts already minified.

However, I thought it was good to submit this issue showing you what line JSLite breaks the syntax, when minifying jQuery.

I also submitted this because I did not notice a particular `$config` option to avoid this issue in the minification process. So just correct me here, if there is a `$config` option to pass to avoid the syntax issue mentioned here, if I missed that option to pass.

_**For reference or testing...**_

I've created a gist of that jQuery and the line that JSLite breaks the syntax of:
https://gist.github.com/theperfectwill/ef1bac5ffb7f06bca3332e362bd455cd#file-jquery-js-L9365

Here is a screenshot of that line:

![image](https://github.com/hexydec/jslite/assets/6123260/362237e3-891d-443f-bfa5-b1e6b7f2fa16)

The issue is that JSLite adds a semi colon at the end of this line/code:
```js
s.crossDomain = originAnchor.protocol + "//" + originAnchor.host !==
```

Making the syntax to be:
```js
s.crossDomain = originAnchor.protocol + "//" + originAnchor.host !==;
```

**Comment by hexydec** [comment]
What version are you running? I took your Gist and couldn't recreate the issue, latest version of JSlite and Torque both minify correctly.

Try it here: https://hexydec.com/apps/minify-js/

I tried it with the full code and no problem, I also cut it down to this:

```javascript
if ( s.crossDomain == null ) {
	urlAnchor = document.createElement( "a" );

	// Support: IE <=8 - 11, Edge 12 - 15
	// IE throws exception on accessing the href property if url is malformed,
	// e.g. http://example.com:80x/
	try {
		urlAnchor.href = s.url;

		// Support: IE <=8 - 11 only
		// Anchor's host property isn't correctly set when s.url is relative
		urlAnchor.href = urlAnchor.href;
		s.crossDomain = originAnchor.protocol + "//" + originAnchor.host !==
			urlAnchor.protocol + "//" + urlAnchor.host;
	} catch ( e ) {

		// If there is an error parsing the URL, assume it is crossDomain,
		// it can be rejected by the transport if it is invalid
		s.crossDomain = true;
	}
}
```

And it produces:

```javascript
if(s.crossDomain==null){urlAnchor=document.createElement("a");try{urlAnchor.href=s.url;urlAnchor.href=urlAnchor.href;s.crossDomain=originAnchor.protocol+"//"+originAnchor.host!==urlAnchor.protocol+"//"+urlAnchor.host}catch(e){s.crossDomain=!0}}
```

**Comment by hexydec** [comment]
I did only do it with all the minification options enabled. If you can find the combo that produced the incorrect result then let me know.
