### ISSUE TITLE
Minification issues on class

### ISSUE THREAD

**Issue by ardivee** [hexydec/jslite#4]
If i write my class like this:

```javascript
class MyClass
{

}
```

It will add a semicolon after MyClass, so it looks like this:

```javascript
class MyClass;{}
```

But when writing it like this, it's all fine.

```javascript
class MyClass {
}
```

**Comment by hexydec** [comment]
Confirmed, I will come back with a fix.

**Comment by hexydec** [comment]
Should be sorted now, will push another release shortly.
